### ISSUE TITLE
Lighter ink shade color

### ISSUE THREAD

**Issue by aminalhazwani** [FirefoxUX/photon-colors#5]
From https://github.com/FirefoxUX/photon/issues/296 by @ericawright

> I'm also in need of something like: `#7878a5`, I can get a similar result if I use Purple60 with 30 alpha, but our purples are too red to replace it.

> almost like a light shade of the ink palette?

**Comment by ericawright** [comment]
@aminalhazwani @brassy- Just reiterating this request for lighter ink shades. Originally I asked for one, but a few more would be beneficial for firefox for ios.

**Comment by aminalhazwani** [comment]
@ericawright I am so sorry I did not followed up on this one. Putting this on my TODO for the week!

**Comment by aminalhazwani** [comment]
<img width="188" alt="screen shot 2018-06-28 at 2 22 09 pm" src="https://user-images.githubusercontent.com/1721875/42061390-d636c38c-7ade-11e8-8e56-222535e100e8.png">

These are the new 50 and 60 shade @ericawright! Would you need more? cc also @shorlander for approval of these new colors.

**Comment by aminalhazwani** [comment]
Hello @ericawright! I talked with Stephen and we defined a potential Ink palette candidate, the colors are the following:

- Ink 40 `#7175A8`
- Ink 50 `#595E91`
- Ink 60 `#474B76`
- Ink 70 `#363959`
- Ink 80 `#202340`
- Ink 90 `#0f1126`

Before shipping it to the colors tokens we would love to hear a feedback from you! Does the palette properly support your work? Any Ink shade that feels out of place? Many Thanks!

**Comment by ericawright** [comment]
@tecgirl, what do you think?

**Comment by garvankeeley** [comment]
@tecgirl the OS X digital color meter gave me (on the screencap you posted in slack):
```
Ink40 #7075A8
Ink50 #595E91
Ink60 #464B76
```

Ink40 is different here than the one in https://github.com/FirefoxUX/photon-colors/issues/5#issuecomment-403430712
Not sure if that is an issue or not.

Edit: I'll do a PR with the colors from that comment above, I don't think pulling the color with the eyedropper as I did is the right way to grab this
